# steps for data preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [5]:
dataset.isnull().any()

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

In [6]:
dataset['Age'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Age, dtype: bool

In [7]:
dataset['Age'].fillna(dataset['Age'].mean(),inplace=True)
dataset['Salary'].fillna(dataset['Salary'].mean(),inplace=True)
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [8]:
dataset['Country'].value_counts()

France     4
Spain      3
Germany    3
Name: Country, dtype: int64

In [9]:
dataset['Age']=dataset['Age'].round()
dataset

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  39.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [10]:
dataset['Purchased'].value_counts()

No     5
Yes    5
Name: Purchased, dtype: int64

In [11]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

In [12]:
x=dataset.iloc[:,0:3].values

In [13]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
y=dataset.iloc[:,-1].values

In [15]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [16]:
y.ndim

1

In [17]:
x.ndim

2

In [18]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
x.shape

(10, 3)

In [20]:
y.shape

(10,)

In [21]:
import sklearn

In [22]:
sklearn.__version__

'0.22.1'

In [23]:
from sklearn.compose import ColumnTransformer#transformation from column
from sklearn.preprocessing import OneHotEncoder#to binary

In [24]:
ct=ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [25]:
x.shape

(10, 5)

In [26]:
#removing dummy variables

In [27]:
x=x[:,1:]

In [28]:
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [29]:
x.shape

(10, 4)

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [32]:
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [33]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-6.54653671e-01, -6.54653671e-01,  7.55609652e-01,
         7.49473254e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.71465267e+00,
        -1.43817841e+00],
       [ 1.52752523e+00, -6.54653671e-01, -1.27872403e+00,
        -8.91265492e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.16247639e-01,
        -2.53200424e-01],
       [ 1.52752523e+00, -6.54653671e-01,  1.74371458e-01,
         6.63219199e-16],
       [-6.54653671e-01, -6.54653671e-01, -5.52176284e-01,
        -5.26656882e-01],
       [-6.54653671e-01,  1.52752523e+00,  2.90619097e-02,
        -1.07356980e+00],
       [-6.54653671e-01, -6.54653671e-01,  1.33684785e+00,
         1.38753832e+00],
       [ 1.52752523e+00, -6.54653671e-01,  1.62746694e+00,
         1.75214693e+00],
       [-6.54653671e-01, -6.54653671e-01, -2.61557187e-01,
         2.93712492e-01]])

In [34]:
import pandas as pd
dataset=pd.read_csv('Titanic.csv')

dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x

array([[-6.54653671e-01, -6.54653671e-01,  7.55609652e-01,
         7.49473254e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.71465267e+00,
        -1.43817841e+00],
       [ 1.52752523e+00, -6.54653671e-01, -1.27872403e+00,
        -8.91265492e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.16247639e-01,
        -2.53200424e-01],
       [ 1.52752523e+00, -6.54653671e-01,  1.74371458e-01,
         6.63219199e-16],
       [-6.54653671e-01, -6.54653671e-01, -5.52176284e-01,
        -5.26656882e-01],
       [-6.54653671e-01,  1.52752523e+00,  2.90619097e-02,
        -1.07356980e+00],
       [-6.54653671e-01, -6.54653671e-01,  1.33684785e+00,
         1.38753832e+00],
       [ 1.52752523e+00, -6.54653671e-01,  1.62746694e+00,
         1.75214693e+00],
       [-6.54653671e-01, -6.54653671e-01, -2.61557187e-01,
         2.93712492e-01]])

In [37]:
x_train.shape

(8, 4)

In [38]:
y_train.shape

(8,)

In [39]:
x_test

array([[ 1.52752523, -0.65465367, -1.27872403, -0.89126549],
       [ 1.52752523, -0.65465367,  1.62746694,  1.75214693]])

In [40]:
y_test

array([0, 0])